# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data', models.DateTimeField()),
                ('local', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legenda', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='images')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto_web.Evento')),
            ],
        ),
    ]
