# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 19:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_web', '0002_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='cod_cpf',
            new_name='CPF',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='end_email',
            new_name='EMail',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='nom_pessoa',
            new_name='Nome',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='dt_cadastro',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='dt_nascimento',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='Data_Cadastro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 8, 19, 9, 54, 109056, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='Data_Nascimento',
            field=models.DateField(default=datetime.datetime(2016, 2, 8, 19, 10, 6, 405009, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
